# -*- coding: utf-8 -*-
"""Desafio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yMjnB22Zl-vmoPbV2vlVFLnixcrLnMRs

**`Desafio: hora da prática`**

Vamos praticar o uso de vários tipos de variáveis e da função input a partir de algumas atividades. Solucione os problemas propostos em código.


**`Coleta e amostragem de dados`**
1. Crie um programa que solicite à pessoa usuária digitar seu nome, e imprima “Olá, [nome]!”.
2. Crie um programa que solicite à pessoa usuária digitar seu nome e idade, e imprima “Olá, [nome], você tem [idade] anos.”.
3. Crie um programa que solicite à pessoa usuária digitar seu nome, idade e altura em metros, e imprima “Olá, [nome], você tem [idade] anos e mede [altura] metros!”.

**`Calculadora com operadores`**
1. Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a soma dos dois valores.
2. Crie um programa que solicite três valores numéricos à pessoa usuária e imprima a soma dos três valores.
3. Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a subtração do primeiro pelo o segundo valor.
4. Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a multiplicação dos dois valores.
5. Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e realize a divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.
6. Crie um programa que solicite dois valores numéricos, um operador e uma potência, e realize a exponenciação entre esses dois valores.
7. Crie um programa que solicite dois valores numéricos, um numerador e um denominador e realize a divisão inteira entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.
8. Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e retorne o resto da divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.
9. Crie um código que solicita 3 notas de um estudante e imprima a média das notas.
10. Crie um código que calcule e imprima a média ponderada dos números 5, 12, 20 e 15 com pesos respectivamente iguais a 1, 2, 3 e 4.

**`Editando textos`**
1. Crie uma variável chamada “frase” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase na tela.
2. Crie um código que solicite uma frase e depois imprima a frase na tela.
3. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras maiúsculas.
4. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras minúsculas.
5. Crie uma variável chamada “frase” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase sem espaços em branco no início e no fim.
6. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim.
7. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim e em letras minúsculas.
8. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “e” trocadas pela letra “f”.
9. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “a” trocadas pela caractere “@”.
10. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as consoantes “s” trocadas pelo caractere “$”.

**`Coleta e amostragem de dados`**
"""

# 1
nome = input("Digite seu nome: ")
print(f"Olá, {nome}!")

# 2
nome = input("Digite seu nome: ")
idade = int(input("Digite a sua idade: "))

print(f"Olá, {nome}, você tem {idade} anos.")

# 3
nome = input("Digite o seu nome: ")
idade = int(input("Digite a sua idade: "))
altura = float(input("Digite a sua altura: "))

print(f"Olá, {nome}, você tem {idade} anos e mede {altura} metros!")

"""**`Calculadora com operadores`**"""

# 1
valor1 = int(input("Digite um número: "))
valor2 = int(input("Digite um novo número: "))
soma = valor1 + valor2

print(f"A soma dos valores é: {soma}")

# 2
valor1 = int(input("Digite um número: "))
valor2 = int(input("Digite um novo número: "))
valor3 = int(input("Digite um terceiro número: "))
soma = valor1 + valor2 + valor3

print(f"A soma dos valores é: {soma}")

# 3
valor1 = int(input("Digite um número: "))
valor2 = int(input("Digite um novo número: "))
subtracao = valor1 - valor2

print(f"A subtração dos valores é: {subtracao}")

# 4
valor1 = int(input("Digite um número: "))
valor2 = int(input("Digite um novo número: "))
multiplicacao = valor1 * valor2

print(f"A multiplicação dos valores é: {multiplicacao}")

# 5
valor1 = int(input("Digite um número: "))
valor2 = int(input("Digite um outro número maior que 0: "))
divisao = valor1 / valor2

print(f"A divisão dos valores é: {divisao}")

# 6
valor1 = int(input("Digite um número: "))
valor2 = int(input("Digite um novo número: "))
exponenciacao = valor1 ** valor2

print(f"A exponenciação dos valores é: {exponenciacao}")

# 7
valor1 = int(input("Digite o primero número: "))
valor2 = int(input("Digite o segundo número que seja maior que 0: "))
divisao_inteira = valor1 // valor2

print(f"A divisão inteira dos valores é: {divisao_inteira}")

# 8
valor1 = int(input("Digite um número: "))
valor2 = int(input("Digite um número maior que 0: "))
resto = valor1 % valor2

print(f"O resto da divisão é: {resto}")

# 9
valor1 = float(input("Digite a primeira nota: "))
valor2 = float(input("Digite a segunda nota: "))
valor3 = float(input("Digite a terceira nota: "))
media = (valor1 + valor2 + valor3) /3

print(f"A média das notas é: {media}")

# 10
parte1 = (5 * 1) + (12 * 2) + (20 * 3) + (15 * 4)
parte2 = 1 + 2 + 3 + 4
media = parte1 / parte2

print(f"A média ponderada é: {media}")

"""**`Editando textos`**"""

# 1
frase = "Jony está estudando Análise de Dados"
print(frase)

# 2
frase = input("Digite uma frase: ")
print(frase)

# 3
frase = input("Digite uma frase: ")

print(frase.upper())

# 4
frase = input("Digite uma frase: ")

print(frase.lower())

# 5
frase = "   Jony está estudando Análise de Dados   "

print(frase.strip())

# 6
frase = input("Digite uma frase: ")

print(frase.strip())

# 7
frase = input("Digite uma frase: ")

print(frase.strip().lower())

# 8
frase = input("Digite uma frase: ")

print(frase.replace("e","f"))

# 9
frase = input("Digite uma frase: ")

print(frase.replace("a","@"))

# 10
frase = input("Digite uma frase: ")

print(frase.replace("s","$"))
